<% MixTemplates.ignore_file_unless(@is_travis?) %>
language: elixir
elixir:
  - 1.4.5
otp_release:
  - 20.0
addons:
  - postgresql: '9.4'
env:
  - MIX_ENV=test
install:
  - mix local.hex --force
  - mix local.rebar --force
  - mix deps.get
jobs:
  include:
    - stage: lint
      script:
        - mix credo
    - stage: test
      script:
        - mix ecto.setup
        - mix test
